<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Erlang.Compiler/Erlang.Compiler.csproj" /><ProjectReference Include="../../src/Erlang.Serialization/Erlang.Serialization.csproj" /><ProjectReference Include="../../src/Erlang.Otp.Behaviours/Erlang.Otp.Behaviours.csproj" /><ProjectReference Include="../../tools/Erlang.Differential/Erlang.Differential.csproj" /><ProjectReference Include="../../tools/Erlang.Style/Erlang.Style.csproj" />
<Reference Include="Microsoft.CodeAnalysis.Workspaces"><HintPath>$(MSBuildToolsPath)/DotnetTools/dotnet-format/Microsoft.CodeAnalysis.Workspaces.dll</HintPath></Reference>
<Reference Include="Microsoft.CodeAnalysis.CSharp.Workspaces"><HintPath>$(MSBuildToolsPath)/DotnetTools/dotnet-format/Microsoft.CodeAnalysis.CSharp.Workspaces.dll</HintPath></Reference>
<Reference Include="System.Composition.AttributedModel"><HintPath>$(MSBuildToolsPath)/DotnetTools/dotnet-format/System.Composition.AttributedModel.dll</HintPath></Reference>
<Reference Include="System.Composition.Runtime"><HintPath>$(MSBuildToolsPath)/DotnetTools/dotnet-format/System.Composition.Runtime.dll</HintPath></Reference>
<Reference Include="System.Composition.Hosting"><HintPath>$(MSBuildToolsPath)/DotnetTools/dotnet-format/System.Composition.Hosting.dll</HintPath></Reference>
<Reference Include="System.Composition.TypedParts"><HintPath>$(MSBuildToolsPath)/DotnetTools/dotnet-format/System.Composition.TypedParts.dll</HintPath></Reference>
</ItemGroup></Project>
