<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Erlang.Compiler/Erlang.Compiler.csproj" /><ProjectReference Include="../../src/Erlang.Serialization/Erlang.Serialization.csproj" /><ProjectReference Include="../../src/Erlang.Otp.Behaviours/Erlang.Otp.Behaviours.csproj" /><ProjectReference Include="../../tools/Erlang.Differential/Erlang.Differential.csproj" /></ItemGroup></Project>
