namespace Erlang.Differential;

public static class BeginOperatorCases
{
    private static Term Success(Term value) => Term.Tuple(Term.A(OracleOutcomeTags.Success), value);

    private static Term Error(Term reason) => Term.Tuple(Term.A(OracleOutcomeTags.Failure), Term.A("error"), reason);

    public static IReadOnlyList<OperatorExpressionCase> All { get; } = [
        new("begin-value", "begin 1,42 end", Success(Term.I(42))),
        new("begin-binding-export", "begin X=40,begin Y=2,X+Y end,{X,Y} end", Success(Term.Tuple(Term.I(40),Term.I(2)))),
        new("begin-order", "begin put(counter,0),put(counter,get(counter)+1),get(counter) end", Success(Term.I(1))),
        new("begin-nested-if", "begin X=42,if X>0 -> begin Y=X,Y end; true -> Y=0 end,Y end", Success(Term.I(42))),
        new("begin-body-exception", "begin error(first),error(second) end", Error(Term.A("first"))),
        new("begin-prebound-badmatch", "begin X=1,begin X=2 end end", Error(Term.Tuple(Term.A("badmatch"),Term.I(2)))),
        new("begin-closure", "begin X=40,F=fun(Y)->begin Z=X+Y,Z end end,F(2) end", Success(Term.I(42))),
        new("bnot-zero", "bnot 0", Success(Term.I(-1))),
        new("bnot-negative", "bnot -1", Success(Term.I(0))),
        new("bnot-big", "bnot 18446744073709551616", Success(new Integer(System.Numerics.BigInteger.Parse("-18446744073709551617")))),
        new("band-positive", "13 band 6", Success(Term.I(4))),
        new(
            "band-negative",
            "-1 band 18446744073709551616",
            Success(new Integer(System.Numerics.BigInteger.Parse("18446744073709551616")))
        ),
        new("bor-big", "18446744073709551616 bor 1", Success(new Integer(System.Numerics.BigInteger.Parse("18446744073709551617")))),
        new(
            "bxor-negative",
            "-1 bxor 18446744073709551616",
            Success(new Integer(System.Numerics.BigInteger.Parse("-18446744073709551617")))
        ),
        new("shift-left", "5 bsl 3", Success(Term.I(40))),
        new("shift-right", "40 bsr 3", Success(Term.I(5))),
        new("shift-right-negative-value", "-5 bsr 1", Success(Term.I(-3))),
        new("shift-left-negative-count", "-5 bsl -1", Success(Term.I(-3))),
        new("shift-right-negative-count", "5 bsr -3", Success(Term.I(40))),
        new("shift-big-value", "1 bsl 64", Success(new Integer(System.Numerics.BigInteger.Parse("18446744073709551616")))),
        new("shift-huge-right-positive", "42 bsr 18446744073709551616", Success(Term.I(0))),
        new("shift-huge-right-negative", "-42 bsr 18446744073709551616", Success(Term.I(-1))),
        new("shift-huge-left-negative", "-42 bsl -18446744073709551616", Success(Term.I(-1))),
        new("shift-huge-zero", "0 bsl 18446744073709551616", Success(Term.I(0))),
        new("shift-huge-left-resource", "1 bsl 18446744073709551616", Error(Term.A("system_limit"))),
        new("shift-huge-right-negative-resource", "1 bsr -18446744073709551616", Error(Term.A("system_limit"))),
        new("bnot-float-error", "bnot 1.0", Error(Term.A("badarith"))),
        new("band-float-error", "1 band 1.0", Error(Term.A("badarith"))),
        new("bor-atom-error", "atom bor 1", Error(Term.A("badarith"))),
        new("bxor-float-error", "1.0 bxor 1", Error(Term.A("badarith"))),
        new("shift-float-count-error", "0 bsl 1.0", Error(Term.A("badarith"))),
        new("shift-float-value-error", "1.0 bsr 1", Error(Term.A("badarith"))),
        new("and-tt", "true and true", Success(Term.A("true"))),
        new("and-tf", "true and false", Success(Term.A("false"))),
        new("and-ft", "false and true", Success(Term.A("false"))),
        new("and-ff", "false and false", Success(Term.A("false"))),
        new("or-tt", "true or true", Success(Term.A("true"))),
        new("or-tf", "true or false", Success(Term.A("true"))),
        new("or-ft", "false or true", Success(Term.A("true"))),
        new("or-ff", "false or false", Success(Term.A("false"))),
        new("xor-tt", "true xor true", Success(Term.A("false"))),
        new("xor-tf", "true xor false", Success(Term.A("true"))),
        new("xor-ft", "false xor true", Success(Term.A("true"))),
        new("xor-ff", "false xor false", Success(Term.A("false"))),
        new("and-invalid-right", "false and 1", Error(Term.A("badarg"))),
        new("or-invalid-right", "true or 1", Error(Term.A("badarg"))),
        new("xor-invalid-left", "1 xor true", Error(Term.A("badarg"))),
        new("strict-and-rhs-exception", "false and error(rhs)", Error(Term.A("rhs"))),
        new("strict-or-rhs-exception", "true or error(rhs)", Error(Term.A("rhs"))),
        new("strict-invalid-lhs-rhs-error", "1 and error(rhs)", Error(Term.A("rhs"))),
        new("bit-precedence", "1 bor 2 band 4", Success(Term.I(1))),
        new("shift-add-left-association", "1 bsl 2 + 1", Success(Term.I(5))),
        new("boolean-precedence", "true or false and false", Success(Term.A("true"))),
        new("andalso-right-association", "true andalso true andalso payload", Success(Term.A("payload"))),
        new("orelse-right-association", "false orelse false orelse payload", Success(Term.A("payload"))),
        new("short-invalid-left", "1 andalso true", Error(Term.Tuple(Term.A("badarg"),Term.I(1)))),
        new("short-binding-discard", "begin true andalso (X=1),Y=2,Y end", Success(Term.I(2))),
        new("strict-binding-export", "begin (X=1)+(Y=2),{X,Y} end", Success(Term.Tuple(Term.I(1),Term.I(2)))),
        new("strict-binding-conflict", "(X=1)+(X=2)", Error(Term.Tuple(Term.A("badmatch"),Term.I(2)))),
        new("guard-bit-operators", "if (bnot 0) =:= -1, (13 band 6) =:= 4, (1 bsl 3) =:= 8 -> yes end", Success(Term.A("yes"))),
        new("guard-strict-failure-alternative", "if false and atom; true xor false -> yes end", Success(Term.A("yes"))),
        new("catch-value", "catch 42", Success(Term.I(42))),
        new("catch-throw", "catch throw(payload)", Success(Term.A("payload"))),
        new("catch-exit", "catch exit(reason)", Success(Term.Tuple(Term.A("EXIT"),Term.A("reason")))),
        new("catch-error-reason", "element(1,element(2,catch error(boom)))", Success(Term.A("boom"))),
        new("catch-error-stack-shape", "is_list(element(2,element(2,catch error(boom))))", Success(Term.A("true"))),
        new("catch-error-stack-nonempty", "length(element(2,element(2,catch (1 div 0)))) > 0", Success(Term.A("true"))),
        new("catch-low-precedence", "catch throw(value) + 1", Success(Term.A("value"))),
        new("catch-nested-begin", "catch begin put(counter,1),throw(done) end", Success(Term.A("done"))),
        new("catch-prebound-binding", "begin X=42,catch begin X=42,throw(done) end,X end", Success(Term.I(42))),
        new("comparison-parentheses", "(1 < 2) =:= true", Success(Term.A("true"))),
        new("send-match-precedence", "begin self() ! X=42,receive X -> X after 0 -> no end end", Success(Term.I(42))),
        new("begin-bit-size", "begin S=4,<<(1 bor 2):S>> end", Success(new BitString([48],4)))
    ];
}
