<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><PackAsTool>true</PackAsTool><ToolCommandName>erlang</ToolCommandName><PackageId>Erlang.Net.Tool</PackageId><Version>0.1.0</Version><Description>Experimental Erlang CLR compiler and hybrid source preprocessor.</Description><PackageReadmeFile>README.md</PackageReadmeFile></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Erlang.Compiler/Erlang.Compiler.csproj" /><None Include="../../README.md" Pack="true" PackagePath="/" /><None Include="../../docs/ROSLYN-LICENSE.txt;../../docs/DOTNET-LICENSE.txt;../../docs/DOTNET-ThirdPartyNotices.txt;../../docs/OTP-LICENSE.txt" Pack="true" PackagePath="licenses/" /></ItemGroup></Project>
